/**
 * Writes ledgerlens/fixtures/plans/README.md from the fixture files themselves: how each plan was
 * produced (from the file's own metadata) and what the analyzer finds in it.
 *
 *   pnpm --filter @ledgerworks/ledgerlens fixtures:describe
 */
import { readdirSync, readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { analyzePlan, parsePlan, walk } from '../src/analyzer/index.js';
import type { SchemaSnapshot } from '../src/schema/snapshot.js';

const dir = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../fixtures/plans');

async function main(): Promise<void> {
  const files = readdirSync(dir)
    .filter((f) => f.endsWith('.json'))
    .sort();
  const out: string[] = [
    '# Plan fixtures (L3.2)',
    '',
    'Every file here is a **real** `EXPLAIN` result saved from a real run on a settled **full** shadow of the 10,000,000-row Ledgerline benchmark database (PostgreSQL 16.15), by `ledgerlens/scripts/capture-plan-fixtures.ts`. Nothing is hand-written or edited: the `plan` field is exactly what the server returned. Each file also holds the SQL, the settings that were `SET LOCAL` for the run, the shadow manifest id, and a snapshot of the schema around the tables in the plan (taken like the product takes it: `describe_schema` through a read-only role, plus table activity).',
    '',
    'The tables named `ll_fixtures.*` are scratch tables created on that shadow by the script (the shadow, never the source) to produce shapes the Ledgerline data does not have. `public.*` is Ledgerline itself. This file is generated by `pnpm fixtures:describe`; the findings below are what the analyzer says today.',
    '',
  ];
  for (const f of files) {
    const d = JSON.parse(readFileSync(path.join(dir, f), 'utf8')) as {
      name: string;
      description: string;
      mode: string;
      sql: string;
      settings: Record<string, string>;
      producedBy: { command: string; capturedAt: string; shadow: { manifestId: string } };
      context: SchemaSnapshot;
      plan: unknown;
    };
    const plan = parsePlan(d.plan);
    const findings = await analyzePlan(plan, {
      snapshot: d.context,
      now: new Date(d.producedBy.capturedAt),
    });
    const shape = [...walk(plan.root)].map((n) => n.nodeType);
    out.push(`## ${f}`, '');
    out.push(d.description, '');
    out.push(
      `- produced by: \`${d.producedBy.command}\` on shadow \`${d.producedBy.shadow.manifestId}\`, ${d.producedBy.capturedAt}`,
    );
    const settings = Object.entries(d.settings);
    if (settings.length)
      out.push(`- settings for the run: ${settings.map(([k, v]) => `\`${k} = ${v}\``).join(', ')}`);
    out.push(
      `- SQL: \`${d.sql.replace(/\s+/g, ' ').slice(0, 220)}${d.sql.length > 220 ? '...' : ''}\``,
    );
    out.push(
      `- plan shape: ${shape.slice(0, 8).join(' > ')}${shape.length > 8 ? ' ...' : ''} (${shape.length} nodes${plan.analyzed ? `, executed in ${plan.executionMs} ms` : ', estimates only'})`,
    );
    out.push(
      findings.length
        ? `- findings (${findings.length}): ${findings.map((x) => `\`${x.kind}\` (${x.severity}, node ${x.nodePath})`).join('; ')}`
        : '- findings: none (a control)',
      '',
    );
  }
  writeFileSync(path.join(dir, 'README.md'), out.join('\n'));
  console.log(`wrote ${path.join(dir, 'README.md')}`);
}

main().catch((e: unknown) => {
  console.error(e);
  process.exit(1);
});
