/**
 * The provider-agnostic LLM interface (C2.3). Nothing here depends on a vendor. Everything a
 * model returns (text, tool names, tool arguments) is UNTRUSTED input to the code that receives it.
 */
import type { LLMError } from './errors.js';

export type JsonSchema = Record<string, unknown>;

export interface SystemMessage {
  role: 'system';
  content: string;
}
export interface UserMessage {
  role: 'user';
  content: string;
}
export interface AssistantMessage {
  role: 'assistant';
  /** null when the turn consists only of tool calls */
  content: string | null;
  toolCalls?: ToolCall[];
}
export interface ToolMessage {
  role: 'tool';
  toolCallId: string;
  name?: string;
  /** DATA, not instructions. The agent loop delimits it; see agent/loop.ts. */
  content: string;
}
export type Message = SystemMessage | UserMessage | AssistantMessage | ToolMessage;

export interface ToolDefinition {
  name: string;
  description: string;
  /** JSON Schema object describing the arguments */
  parameters: JsonSchema;
}

export interface ToolCall {
  /** provider-supplied, or generated by the adapter when the server omitted it (see `quirks`) */
  id: string;
  /** untrusted: may name a tool that was never offered */
  name: string;
  /** parsed arguments; untrusted and unvalidated. `undefined` when `argumentsError` is set. */
  arguments: unknown;
  /** the arguments exactly as the model produced them (a JSON string) */
  rawArguments: string;
  /** set when rawArguments is not valid JSON: the call is passed on flagged, never repaired silently */
  argumentsError?: string;
}

export type FinishReason = 'stop' | 'tool_calls' | 'length' | 'content_filter' | 'other';

export interface Usage {
  promptTokens: number;
  completionTokens: number;
  totalTokens: number;
  /** 'provider' = reported by the server; 'estimated' = our own rough count (about 4 characters per token) */
  source: 'provider' | 'estimated';
}

/** Rate-limit information read from response headers, when the server sends it. */
export interface RateLimitInfo {
  remainingRequests?: number;
  remainingTokens?: number;
  /** milliseconds until the request budget resets, relative to when the response arrived */
  resetRequestsMs?: number;
  resetTokensMs?: number;
}

export interface ProviderRouting {
  /** provider that produced the result */
  provider: string;
  /** providers passed over before it, with the reason */
  skipped: { provider: string; reason: string }[];
}

export interface ChatResult {
  content: string | null;
  toolCalls: ToolCall[];
  finishReason: FinishReason;
  usage: Usage;
  model?: string;
  /** id of the provider (adapter) that answered */
  provider: string;
  /** deviations from the standard format that the adapter normalised, e.g. 'tool_call_id_generated' */
  quirks?: string[];
  rateLimit?: RateLimitInfo;
  /** set by a fallback chain: which provider handled the call and why others were skipped */
  routing?: ProviderRouting;
}

export type ToolChoice = 'auto' | 'none' | 'required' | { name: string };

export interface ChatRequest {
  messages: Message[];
  tools?: ToolDefinition[];
  toolChoice?: ToolChoice;
  temperature?: number;
  maxTokens?: number;
  /** ask for a JSON object as the reply */
  jsonMode?: boolean;
  /** cancels the call; the result is an LLMError of kind 'cancelled' */
  signal?: AbortSignal;
  /** per-call timeout override, ms */
  timeoutMs?: number;
  /** lets a fallback chain keep one conversation on one provider */
  conversationId?: string;
}

export type StreamEvent =
  | { type: 'text_delta'; text: string }
  | { type: 'tool_call_start'; index: number; id: string; name: string }
  | { type: 'tool_call_delta'; index: number; argumentsDelta: string }
  | { type: 'tool_call_end'; index: number }
  | { type: 'usage'; usage: Usage }
  /** last event of a successful stream; `result` is the assembled response */
  | { type: 'done'; result: ChatResult }
  /** last event of a failed stream. Streams do not throw provider errors. */
  | { type: 'error'; error: LLMError };

export type CapabilitySource = 'declared' | 'probed' | 'unknown';

export interface Capability<T> {
  /** null when unknown */
  value: T | null;
  source: CapabilitySource;
  /** ISO time of the probe, for source 'probed' */
  probedAt?: string;
}

export interface Capabilities {
  tools: Capability<boolean>;
  streaming: Capability<boolean>;
  jsonMode: Capability<boolean>;
  parallelToolCalls: Capability<boolean>;
  /** context window in tokens, if known */
  maxContext: Capability<number>;
}

export const unknownCapabilities = (): Capabilities => ({
  tools: { value: null, source: 'unknown' },
  streaming: { value: null, source: 'unknown' },
  jsonMode: { value: null, source: 'unknown' },
  parallelToolCalls: { value: null, source: 'unknown' },
  maxContext: { value: null, source: 'unknown' },
});

export interface LLMProvider {
  /** stable id used in traces, e.g. "groq" or "fake" */
  readonly id: string;
  readonly model: string;
  capabilities(): Capabilities;
  /** Merges new capability information (for example from a probe). */
  updateCapabilities?(patch: Partial<Capabilities>): void;
  /** Throws LLMError. */
  chat(request: ChatRequest): Promise<ChatResult>;
  /** Yields events; a provider failure arrives as a final `error` event instead of an exception. */
  stream(request: ChatRequest): AsyncIterable<StreamEvent>;
  listModels?(signal?: AbortSignal): Promise<string[]>;
}

/** Time, injectable so tests never sleep. */
export interface Clock {
  now(): number;
  sleep(ms: number, signal?: AbortSignal): Promise<void>;
}

export const systemClock: Clock = {
  now: () => Date.now(),
  sleep: (ms, signal) =>
    new Promise((resolve, reject) => {
      if (signal?.aborted) return reject(signal.reason ?? new Error('aborted'));
      const onAbort = (): void => {
        clearTimeout(t);
        reject(signal?.reason ?? new Error('aborted'));
      };
      const t = setTimeout(() => {
        signal?.removeEventListener('abort', onAbort);
        resolve();
      }, ms);
      signal?.addEventListener('abort', onAbort, { once: true });
    }),
};

/** A clock for tests: time moves only when something sleeps or the test advances it. */
export class ManualClock implements Clock {
  private t: number;
  readonly sleeps: number[] = [];
  constructor(start = 1_000_000) {
    this.t = start;
  }
  now(): number {
    return this.t;
  }
  advance(ms: number): void {
    this.t += ms;
  }
  async sleep(ms: number, signal?: AbortSignal): Promise<void> {
    if (signal?.aborted) throw signal.reason ?? new Error('aborted');
    this.sleeps.push(ms);
    this.t += ms;
  }
}

/** rough token estimate used when a server reports no usage: about 4 characters per token */
export const estimateTokens = (text: string): number => Math.ceil(text.length / 4);
